gitlab-ci.yml: automatically tag the repository
Automatically tag the repository when we bump
the version of container image.

Related-to: TOR-1942

Signed-off-by: Dejan Jesenko <dejan.jesenko@toradex.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -29,6 +29,7 @@ services:
 
 stages:
   - lint
+  - repository tagging
   - build
   - build-multiarch
   - deploy
@@ -160,6 +161,31 @@ lint_dockerfile:
     # - DL3008: pin versions in apt-get install
     # - DL3029 (do not use --platform flag with FROM)
     - hadolint Dockerfile.* --failure-threshold warning --info DL3008 --info DL3029
+
+# Make sure to create access token in "Settings/Access Tokens" section with "write_repository" scope selected.
+# Then in "Settings/CI/CD/" section add a variable with key "GIT_TOKEN" and a value of the access token. Also mask the variable.
+tag:
+  stage: repository tagging
+  needs: []
+  before_script:
+    - if [ -z ${GIT_TOKEN} ]; then echo "Missing variable GIT_TOKEN." && exit 1; fi
+    - TAGS="chromium-${CHROMIUM_MAJOR}.${CHROMIUM_MINOR}.${CHROMIUM_PATCH}
+            chromium-x11-${CHROMIUM_X11_MAJOR}.${CHROMIUM_X11_MINOR}.${CHROMIUM_X11_PATCH}
+            cog-${COG_MAJOR}.${COG_MINOR}.${COG_PATCH}"
+  script:
+  - apk update && apk add git
+  - git remote set-url origin https://gitlab-ci-token:${GIT_TOKEN}@${CI_REPOSITORY_URL#*@}
+  - for TAG in ${TAGS};
+      do
+        if git ls-remote --tags origin  | grep ${TAG} > /dev/null; then
+          echo "${TAG} tag already exists.";
+        else
+          echo "Tagging repository with ${TAG} tag.";
+          git tag --delete ${TAG} > /dev/null 2>&1 || true;
+          git tag ${TAG};
+          git push -o ci.skip origin ${TAG};
+        fi
+      done
 
 # Enable experimental features in Docker client (experimental feature are needed for manifest)
 .do_docker_experimental: &do_docker_experimental
